#!/usr/bin/env python3
"""Mirror the university's SPECIAL-USE folder flags into the local Dovecot.

Runs as root from the entrypoint. It logs in to the university as an enrolled
user, reads which folders the university itself marks as \\Sent, \\Drafts, \\Trash,
\\Junk, \\Archive (RFC 6154 SPECIAL-USE - the university's OWN designation, so no
folder names are hardcoded and it adapts to any locale), and writes a Dovecot
include that tags the matching local folders with the same roles. Any mail client
then auto-recognizes the localized folders (e.g. "Gesendete Elemente" as Sent) and
stops creating its own English duplicates.

Exit codes: 10 = the generated include changed (caller should reload Dovecot);
0 = already up to date; 1 = could not discover yet (no enrolled user, or the
university was unreachable) - the caller just tries again later.
"""
import base64
import glob
import imaplib
import os
import re
import ssl
import sys

sys.path.insert(0, "/usr/local/bin")
import authcheck as a  # decrypt_secret + upstream_user

OUT = "/etc/dovecot/special-use.conf"
HOST = os.environ.get("UPSTREAM_IMAP_HOST", "email.uni-graz.at")
PORT = int(os.environ.get("UPSTREAM_IMAP_PORT", "993"))
# The RFC 6154 roles we mirror. We take whatever the university advertises; we do
# not assume any particular folder name.
ROLE_FLAGS = ("\\Sent", "\\Drafts", "\\Trash", "\\Junk", "\\Archive", "\\All", "\\Flagged")
_LIST_RE = re.compile(rb'^\((?P<flags>[^)]*)\)\s+(?:"[^"]*"|NIL)\s+(?P<name>.+)$')


def log(msg):
    sys.stderr.write(f"[special-use] {msg}\n")


def _imap_utf7_decode(s: str) -> str:
    """Decode IMAP modified UTF-7 (RFC 3501) folder names to real UTF-8, so the
    Dovecot config matches the folder (e.g. 'Entw&APw-rfe' -> 'Entwürfe')."""
    out = []
    i = 0
    while i < len(s):
        c = s[i]
        if c == "&":
            j = s.find("-", i)
            if j == -1:
                out.append(s[i:])
                break
            chunk = s[i + 1:j]
            if chunk == "":
                out.append("&")  # '&-' is a literal '&'
            else:
                b64 = chunk.replace(",", "/")
                b64 += "=" * (-len(b64) % 4)
                out.append(base64.b64decode(b64).decode("utf-16-be"))
            i = j + 1
        else:
            out.append(c)
            i += 1
    return "".join(out)


def enrolled_users():
    return [os.path.basename(d.rstrip("/")) for d in glob.glob("/mail/.creds/*/")
            if os.path.isfile(os.path.join(d, "upass.enc"))]


def discover(email: str) -> dict:
    """Return {folder_name: role_flag} from the university's own SPECIAL-USE flags."""
    pw = a.decrypt_secret(open(f"/mail/.creds/{email}/upass.enc", "rb").read())
    m = imaplib.IMAP4_SSL(HOST, PORT, ssl_context=ssl.create_default_context(), timeout=30)
    m.login(a.upstream_user(email), pw)
    try:
        lines = m.list()[1] or []
    finally:
        try:
            m.logout()
        except Exception:  # noqa: BLE001
            pass
    mapping = {}
    for raw in lines:
        mm = _LIST_RE.match(raw.strip())
        if not mm:
            continue
        flags = mm.group("flags").decode("ascii", "replace").split()
        role = next((f for f in flags if f in ROLE_FLAGS), None)
        if not role:
            continue
        name = mm.group("name").strip()
        if name.startswith(b'"') and name.endswith(b'"'):
            name = name[1:-1]
        mapping[_imap_utf7_decode(name.decode("ascii", "replace"))] = role
    return mapping


def render(mapping: dict) -> str:
    if not mapping:
        return ""
    blocks = ["# Auto-generated from the university's own SPECIAL-USE flags.",
              "# Do not edit; regenerated by special_use.py.", ""]
    for name in sorted(mapping):
        esc = name.replace("\\", "\\\\").replace('"', '\\"')
        blocks.append(f'mailbox "{esc}" {{\n  special_use = {mapping[name]}\n}}')
    return "\n".join(blocks) + "\n"


def main() -> int:
    users = enrolled_users()
    if not users:
        return 1
    mapping = None
    for email in users:
        try:
            mapping = discover(email)
            break
        except Exception as exc:  # noqa: BLE001 - unreachable/auth: try the next user, else retry later
            log(f"{email}: {exc.__class__.__name__}: {exc}")
    if mapping is None:
        return 1
    new = render(mapping)
    old = open(OUT).read() if os.path.exists(OUT) else None
    if new != old:
        with open(OUT, "w") as fh:
            fh.write(new)
        log(f"tagged {len(mapping)} folder(s): "
            + ", ".join(f"{n}={r}" for n, r in sorted(mapping.items())))
        return 10
    return 0


if __name__ == "__main__":
    sys.exit(main())
